monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        device.routes.default-sink-volume = 1.0
      }
    }
  }
]
