PACKAGE_NAME="virtio_snd"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="virtio_snd"
DEST_MODULE_LOCATION[0]="/kernel/sound/virtio"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
AUTOINSTALL="yes"
