# vim: ft=dockerfile
FROM platypew/pwnbox2:latest

ENV USER pwnbox
USER $USER

RUN sudo pacman -R --noconfirm gnu-netcat && \
    sudo pacman -Syu --noconfirm --overwrite='*' arp-scan autorecon commix crackmapexec creddump crunch dbd \
    dns2tcp dnsenum dnsrecon enum4linux expect finalrecon fping hashcat hashcat-utils hping \
    i2c-tools ike-scan inetsim iodine john laudanum lbd ldapenum masscan mimikatz mitmproxy nasm \
    nbtscan ncrack netsed netsniff-ng net-snmp ngrep nikto onesixtyone patator rbndr recon-ng \
    redsocks rustscan samdump2 scalpel seclists set sleuthkit smbmap snmpcheck socat spiderfoot \
    spike swaks tcpreplay thc-ipv6 thc-pptp-bruter traceroute udptunnel unix-privesc-check upx \
    wafw00f wce webshells whatweb whois windows-binaries && \
    yes | sudo pacman -Sdd gnu-netcat && \
    if [ "$(uname -m)" == "aarch64" ]; then \
        wget -O /tmp/donut.pkg.tar.zst \
            "https://github.com/PlatyPew/pwnbox2-repo/blob/master/x86_64/donut-368.dafea17-3-x86_64.pkg.tar.zst?raw=true" && \
        sudo pacman -U --arch x86_64 --noconfirm /tmp/donut.pkg.tar.zst ; \
    fi && \
    sudo mkdir /etc/samba && \
    sudo wget -O /etc/samba/smb.conf \
        "https://raw.githubusercontent.com/samba-team/samba/master/examples/smb.conf.default" && \
    sudo pacman -S --noconfirm empire && \
    yay -Scc --noconfirm && yay -Rsc --noconfirm $(yay -Qtdq) || true && \
    sudo rm -rf /home/$USER/.zshrc.pre-oh-my-zsh /home/$USER/.zsh_history /home/$USER/.bash_profile \
         /home/$USER/.wget-hsts /home/$USER/.bash_logout /home/$USER/.bundle /tmp/* /var/cache \
         /home/$USER/.cache/pip /home/$USER/.cache/yay && \
    sudo updatedb

USER root
