# vim: ft=dockerfile
FROM platypew/pwnpad:latest

ENV USER pwnpad
USER $USER

RUN sudo pacman -R --noconfirm gnu-netcat && \
    sudo pacman -Syu --noconfirm --overwrite='*' arp-scan autorecon commix creddump \
    crunch dbd dns2tcp dnsenum dnsrecon empire enum4linux-ng expect finalrecon fping hashcat \
    hashcat-utils hping i2c-tools ike-scan inetsim iodine pwnpad/john laudanum lbd ldapenum \
    mimikatz nasm nbtscan ncrack netsed netsniff-ng net-snmp ngrep nikto onesixtyone patator \
    proxychains-ng rbndr recon-ng redsocks rustscan samdump2 scalpel seclists sleuthkit smbmap \
    snmpcheck socat swaks tcpreplay thc-ipv6 thc-pptp-bruter traceroute udptunnel \
    unix-privesc-check upx wafw00f wce webshells whatweb whois windows-binaries && \
    sudo pacman -Rdd --noconfirm impacket && yay -S --noconfirm python-impacket-git && \
    yes | sudo pacman -Sdd gnu-netcat && \
    sudo mkdir /etc/samba && \
    sudo wget -O /etc/samba/smb.conf \
        "https://raw.githubusercontent.com/samba-team/samba/master/examples/smb.conf.default" && \
    sudo pacman -S --noconfirm xorg-server-xvfb x11vnc novnc xdotool gnu-free-fonts i3-wm i3status && \
    pip install websockify crackmapexec && \
    yay -Scc --noconfirm && yay -Rsc --noconfirm $(yay -Qtdq) || true && \
    sudo mv /usr/share/locale/locale.alias /usr/share/locale/en_US /tmp && \
    sudo rm -rf /usr/share/locale/* && sudo mv /tmp/locale.alias /tmp/en_US /usr/share/locale && \
    sudo rm -rf /home/$USER/.zshrc.pre-oh-my-zsh /home/$USER/.zsh_history /home/$USER/.bash_profile \
         /home/$USER/.wget-hsts /home/$USER/.bash_logout /home/$USER/.bundle /tmp/* /var/cache \
         /home/$USER/.cache/pip /home/$USER/.cache/yay /home/$USER/.npm /var/log/* && \
    sudo updatedb

USER root
