#!/usr/bin/env bash

VERSION="v1.1.3"

# Constant variables
P2=`basename "$0"`
MOUNTPOINT="$HOME/.local/share/pwnpad/mounts"

# Print general usage and exits
USAGE() {
    printf "USAGE:
  ${P2} <SUBCOMMAND>

SUBCOMMAND:
  help      You're looking at the help page
  build     Build Docker image
  attach    Attach into container
  rm        Remove container and its volumes
  kill      Stop container from running
  volume    Enter into container's volume
  ls        List pwnpad instances
  update    Update image to the latest build
  version   Show version number of PwnPad

HELP:
  ${P2} build -h
  ${P2} attach -h
  ${P2} ls -h
  ${P2} rm -h\n"
}

# Build docker image
BUILD() {
    BUSE() {
        printf "USAGE:
  ${P2} build [OPTIONS]
OPTIONS:
  -h    You're looking at the help page
  -p    platform
          linux/amd64, linux/arm64
  -i    select image (default: latest)
          lite, latest, bare\n"
    }

    root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

    platform=""
    tag="latest"
    dockerfile="Dockerfile"

    shift
    while getopts ":i:p:h" options
    do
        case $options in
            p) platform="--platform $OPTARG"
                ;;
            i) tag="$OPTARG"
                ;;
            h)
                BUSE
                exit 0
                ;;
            *)
                BUSE
                exit 1
                ;;
        esac
    done

    if [ ${tag} == "lite" ]; then
        dockerfile="Dockerfile-lite"
    fi

    if [ ${tag} == "bare" ]; then
        dockerfile="Dockerfile-bare"
    fi

    if [ ! -d "${root}/docker" ]; then
        printf "You may not have the full Git repository installed\n"
        exit 1
    fi

    docker image build $platform -f $root/docker/${dockerfile} -t platypew/pwnpad:${tag} $root
}

# Start and attach docker container
ATTACH() {
    AUSE() {
        printf "USAGE:
  ${P2} attach [OPTIONS] <BOX>
OPTIONS:
  -h    You're looking at the help page
  -P    use privileged mode (not recommended)
  -S    use sys_admin capability (required for chroot)
  -X    support X11 forwarding
  -D    run as daemon mode
  -e    use environmental variables
          FOO=bar
  -d    display (use with -X)
  -p    port range (default: 22, default port will map to random host port between 40000 and 40999)
          1337:1337
          1337-31337:1337-31337
  -v    mount volumes
          /foo/bar:/foo/bar
  -i    select image (default: latest)
          lite, latest\n"
    }

    env=""
    volume=""
    admin=""
    priv=""
    xsupport=""
    display=""
    image="latest"

    detach=0

    shift
    while getopts ":PSXDe:d:p:v:i:h" options
    do
        case $options in
            P) priv="--privileged"
                ;;
            S)
                if [[ $(uname -m) != "x86_64" ]]; then
                    admin="--cap-add=SYS_ADMIN"
                fi
                ;;
            X) xsupport="-v /tmp/.X11-unix:/tmp/.X11-unix:rw"
                ;;
            D) detach=1
                ;;
            d) display="$OPTARG"
                ;;
            e) env="${env} -e $OPTARG"
                ;;
            p) port="${port} -p $OPTARG"
                ;;
            v) volume="${volume} -v $OPTARG"
                ;;
            i) image="$OPTARG"
                ;;
            h)
                AUSE
                exit 0
                ;;
            *)
                AUSE
                exit 1
                ;;
        esac
    done
    shift $(($OPTIND - 1))

    box_name=${1}

    if [ -z ${box_name} ]; then
        AUSE
        exit 1
    fi


    # Check if there's display running x11
    if [[ ! -z $xsupport ]]; then
        if [[ ! -d "/tmp/.X11-unix" ]]; then
            printf "/tmp/.X11-unix not found\n"
            exit 1
        fi

        if [[ -z $display ]]; then
            if [[ $OSTYPE == 'darwin'* ]]; then
                display="host.docker.internal:0"
            else
                display=$DISPLAY
            fi
        fi

        xsupport="${xsupport} -e DISPLAY=${display}"
    fi

    tz=""
    if [[ $OSTYPE == 'darwin'* ]]; then
        tz=$(readlink /etc/localtime | sed 's#/var/db/timezone/zoneinfo/##g')
    else
        tz=$(readlink /etc/localtime | sed 's#/usr/share/zoneinfo/##g')
    fi

    printf "Making directory...\n"
    mkdir $MOUNTPOINT/${box_name} 2> /dev/null
    printf "Directory located at: $MOUNTPOINT/${box_name}\n"

    # Attaches if container exists
    if [ $(docker container ls -a --filter "name=^/${box_name}$" --format '{{.Names}}') ]; then
        printf "Container exists, reattaching...\n"
        docker container start ${box_name} > /dev/null
    else
        docker container run -it -d \
            -h ${box_name} \
            --name ${box_name} \
            -e TZ=${tz} \
            --cap-add=SYS_PTRACE \
            --cap-add=NET_ADMIN \
            $admin \
            --security-opt seccomp=unconfined \
            --mount type=bind,source="$MOUNTPOINT/${box_name}",target=/mnt/shared \
            --sysctl net.ipv6.conf.all.disable_ipv6=0 \
            --device /dev/net/tun \
            --cgroupns=host \
            -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
            --tmpfs /run \
            --tmpfs /tmp:exec \
            ${xsupport} \
            ${priv} \
            $env $port $volume \
            platypew/pwnpad:${image} sh > /dev/null

        if [ $? -ne 0 ]; then
            printf "An error has occured. Check arguments\n\n"
            AUSE
            exit 1
        fi
    fi

    if [ $detach -eq 0 ]; then
        docker container exec -it "${box_name}" su pwnpad
    fi
}

# Removes pwnpad
RM() {
    RUSE() {
        printf "USAGE:
  ${P2} rm [OPTIONS] <BOX>
OPTIONS:
  -h    You're looking at the help page
  -f    forcefully remove mounted shared directory\n"
    }

    force=0

    shift
    while getopts ":fh" options
    do
        case $options in
            f) force=1
                ;;
            h)
                RUSE
                exit 0
                ;;
            *)
                RUSE
                exit 1
                ;;
        esac
    done
    shift $(($OPTIND - 1))

    box_name=${1}

    if [ -z ${box_name} ]; then
        RUSE
        exit 1
    fi

    printf "Are you sure you want to remove ${box_name}? This cannot be undone! (y/n) "
    read confirmation

    if [ -z $confirmation ] || [ $confirmation != "y" ]; then
        exit 0
    fi

    printf "Attempting to remove container\n"
    docker container rm ${box_name} -f &> /dev/null

    if [ $? -ne 0 ]; then
        printf "Container does not exist\n\n"
        RUSE
        exit 1
    fi

    printf "Cleaning directory\n"
    if [ $force -eq 0 ]; then
        rmdir $MOUNTPOINT/${box_name} 2> /dev/null

        if [ $? -ne 0 ]; then
            printf "Directory not empty, not removing...\n"
        fi
    else
        if type trash &> /dev/null; then
            trash -F $MOUNTPOINT/${box_name}
        else
            rm -rvf $MOUNTPOINT/${box_name}
        fi
    fi

}

KILL() {
    KUSE() {
        printf "USAGE:
  ${P2} kill <BOX>\n"
    }
    if [ -z $2 ] ; then
        KUSE
        exit 1
    fi

    box_name=${2}

    printf "Are you sure you want to kill ${box_name}? This will stop all processes running! (y/n) "
    read confirmation

    if [ -z $confirmation ] || [ $confirmation != "y" ]; then
        exit 0
    fi

    docker container stop "${box_name}"
}

VOLUME() {
    VUSE() {
        printf "USAGE:
  ${P2} volume <BOX>\n"
    }
    if [ -z $2 ]; then
        VUSE
        exit 1
    fi

    cd "$MOUNTPOINT/$2" 2> /dev/null
    exec $SHELL

    if [ $? -ne 0 ]; then
        VUSE
        exit 1
    fi
}

LIST() {
    LUSE() {
        printf "USAGE:
  ${P2} ls [OPTIONS]
OPTIONS:
  -h    You're looking at the help page
  -l    list verbosely\n"
    }

    shift
    while getopts ":lh" options
    do
        case $options in
            l) long=1
                ;;
            h)
                LUSE
                exit 0
                ;;
            *)
                LUSE
                exit 1
                ;;
        esac
    done
    shift $(($OPTIND - 1))

    if [[ -z $long ]]; then
        docker container ls -a --filter "ancestor=platypew/pwnpad:latest" --filter "ancestor=platypew/pwnpad:lite" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
    else
        docker container ls -a --filter "ancestor=platypew/pwnpad:latest" --filter "ancestor=platypew/pwnpad:lite" --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Size}}\t{{.Mounts}}\t{{.RunningFor}}\t{{.Ports}}"
    fi
}

UPDATE() {
    DIR=$(dirname $0)

    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) && ${DIR} != "/opt/homebrew"* ]]; then
        git -C $DIR fetch origin master && git -C $DIR pull origin master --rebase
    fi

    boxexists=$(docker container ls -a --filter "ancestor=platypew/pwnpad:latest" --filter "ancestor=platypew/pwnpad:lite" --format "table {{.Names}}\t{{.Status}}" | tail -n +2)
    if [[ ! -z $boxexists ]]; then
        printf "You have existing instances running:\n"
        echo "$boxexists"

        printf "\nUpdating will leave dangling images which may take up space and instances will no longer be tracked\n"
        printf "Updating will NOT delete any instances you have\n"
        printf "Are you sure you want to update? This cannot be undone! (y/n) "
        read confirmation

        if [ -z $confirmation ] || [ $confirmation != "y" ]; then
            exit 0
        fi
    fi


    beforeid=$(docker image ls platypew/pwnpad:lite | tail -n 1 | awk '{print $3}')
    docker image pull platypew/pwnpad:lite
    afterid=$(docker image ls platypew/pwnpad | grep none | awk '{print $3}')
    if [[ $beforeid == $afterid ]]; then
        docker image rm -f $beforeid
    fi

    beforeid=$(docker image ls platypew/pwnpad:latest | tail -n 1 | awk '{print $3}')
    docker image pull platypew/pwnpad:latest
    afterid=$(docker image ls platypew/pwnpad | grep none | awk '{print $3}')
    if [[ $beforeid == $afterid ]]; then
        docker image rm -f $beforeid
    fi
}

if ! docker version >/dev/null 2>&1; then
    printf "NOTICE:
  Cannot connect to the Docker daemon. Is the docker daemon running?\n\n"
    USAGE
    exit 1
fi

if [ -z ${1} ]; then
    USAGE
    exit 1
fi

if [ ! -d ${MOUNTPOINT} ]; then
    mkdir -p ${MOUNTPOINT}
fi

case ${1} in
    build) BUILD $@
        ;;
    attach) ATTACH $@
        ;;
    kill) KILL $@
        ;;
    rm) RM $@
        ;;
    volume) VOLUME $@
        ;;
    ls) LIST $@
        ;;
    update) UPDATE
        ;;
    version) printf "${VERSION}\n"
        ;;
    help)
        USAGE
        exit 0
        ;;
    *)
        USAGE
        exit 1
        ;;
esac
