local wk = require("which-key")

wk.setup({
    ignore_missing = true,
})

wk.register({
    F = { "<Cmd>lua vim.lsp.buf.format()<CR>", "Format code" },
    T = { "<Cmd>Transparency<CR>", "Toggle Transparency" },
    i = { "<Cmd>Mason<CR>", "Installer" },
    o = { "<Cmd>NvimTreeToggle<CR>", "File Explorer" },
    u = { "<Cmd>UndotreeToggle<CR>", "Toggle UndoTree" },
    m = { "<Cmd>MarkdownPreviewToggle<CR>", "Toggle Markdown Preview" },
    c = {
        name = "Copilot",
        t = { "<Cmd>Copilot toggle<CR>", "Toggle Copilot" },
        p = { "<Cmd>Copilot panel<CR>", "Copilot Panel" },
        s = { "<Cmd>Copilot status<CR>", "Copilot Status" },
    },
    d = {
        name = "Debugger",
        C = { "<Cmd>lua require'dap'.disconnect()<CR>", "Close" },
        R = { "<Cmd>lua require'dap'.repl.open()<CR>", "REPL" },
        S = { "<Cmd>lua require'dap'.step_into()<CR>", "Step Into" },
        a = { "<Cmd>lua _G.dap_args()<CR>", "Set Program Arguments" },
        b = { "<Cmd>lua require'dap'.toggle_breakpoint()<CR>", "Toggle Breakpoint" },
        c = { "<Cmd>lua require'dap'.continue()<CR>", "Continue" },
        e = { "<Cmd>lua require'dapui'.eval()<CR>", "Evaluate" },
        o = { "<Cmd>lua require'dap'.step_out()<CR>", "Step Out" },
        s = { "<Cmd>lua require'dap'.step_over()<CR>", "Step Over" },
        u = { "<Cmd>lua require'dapui'.toggle()<CR>", "Open UI" },
    },
    f = {
        name = "Telescope",
        C = { "<Cmd>Telescope git_commits<CR>", "Commits" },
        D = { "<Cmd>Telescope diagnostics<CR>", "Workspace Diagnostics" },
        G = { "<Cmd>Telescope git_status<CR>", "Git Status Files" },
        M = { "<Cmd>Telescope keymaps<CR>", "Mappings" },
        b = { "<Cmd>Telescope buffers<CR>", "Buffers" },
        c = { "<Cmd>Telescope git_bcommits<CR>", "Commits for Buffer" },
        f = { "<Cmd>Telescope find_files<CR>", "Files" },
        g = { "<Cmd>Telescope git_files<CR>", "Git Files" },
        h = { "<Cmd>Telescope command_history<CR>", "Command History" },
        m = { "<Cmd>Telescope marks<CR>", "Marks" },
        r = { "<Cmd>Telescope live_grep<CR>", "Ripgrep" },
        s = { "<Cmd>Telescope spell_suggest<CR>", "Spell Suggest" },
    },
    g = {
        name = "Git",
        R = { "<Cmd>Gitsigns reset_buffer<CR>", "Reset Buffer" },
        S = { "<Cmd>Gitsigns stage_buffer<CR>", "Stage Buffer" },
        U = { "<Cmd>Gitsigns reset_buffer_index<CR>", "Reset Buffer Index" },
        ["["] = { "<Cmd>Gitsigns prev_hunk<CR>", "Previous Hunk" },
        ["]"] = { "<Cmd>Gitsigns next_hunk<CR>", "Next Hunk" },
        b = { "<Cmd>Gitsigns blame_line<CR>", "Blame Line" },
        d = { "<Cmd>Gitsigns diffthis<CR>", "Reset Buffer Index" },
        p = { "<Cmd>Gitsigns preview_hunk<CR>", "Preview Hunk" },
        r = { "<Cmd>Gitsigns reset_hunk<CR>", "Reset Hunk" },
        s = { "<Cmd>Gitsigns stage_hunk<CR>", "Stage Hunk" },
        t = { "<Cmd>Gitsigns toggle_word_diff<CR>", "Toggle Word Diff" },
        u = { "<Cmd>Gitsigns undo_stage_hunk<CR>", "Undo Stage Hunk" },
    },
    I = {
        name = "Instant",
        Q = { "<Cmd>call v:lua.InstantStopServer()<CR>", "Stop Instant Server" },
        j = { "<Cmd>call v:lua.InstantJoinSession()<CR>", "Join Instant Session" },
        q = { "<Cmd>call v:lua.InstantStopSession()<CR>", "Stop Instant Session" },
        s = { "<Cmd>call v:lua.InstantStartSession()<CR>", "Start Instant Session" },
    },
    l = {
        name = "LSP",
        D = { "<Cmd>Lspsaga show_line_diagnostics<CR>", "Show Line Diagnostics" },
        ["["] = { "<Cmd>Lspsaga diagnostic_jump_prev<CR>", "Previous Diagnostic" },
        ["]"] = { "<Cmd>Lspsaga diagnostic_jump_next<CR>", "Next Diagnostic" },
        c = { "<Cmd>Lspsaga code_action<CR>", "Code Action" },
        d = { "<Cmd>Lspsaga show_cursor_diagnostics<CR>", "Show Cursor Diagnostics" },
        f = { "<Cmd>Lspsaga lsp_finder<CR>", "Find Reference" },
        h = { "<Cmd>Lspsaga hover_doc<CR>", "Docs" },
        i = { "<Cmd>LspInfo<CR>", "LSP Info" },
        p = { "<Cmd>Lspsaga peek_definition<CR>", "Preview Definition" },
        r = { "<Cmd>Lspsaga rename<CR>", "Rename Variable" },
    },
    r = {
        name = "Runner",
        C = { "<Plug>SnipReplMemoryClean", "Clean REPL memory" },
        R = { "<Plug>SnipReset", "Reset SnipRun" },
        c = { "<Plug>SnipClose", "Close SnipRun" },
        i = { "<Plug>SnipInfo", "Get SnipRun Info" },
        r = { "<Plug>SnipRun", "Run Code" },
        t = { "<Plug>SnipTerminate", "Terminate SnipRun" },
    },
}, { mode = "n", prefix = "," })

wk.register({
    c = { "<Cmd>lua require('Comment.api').call('toggle_linewise_op')<CR>g@", "Comment" },
    g = {
        name = "Git",
        s = { "<Cmd>Gitsigns stage_hunk<CR>", "Stage Hunk" },
        u = { "<Cmd>Gitsigns undo_stage_hunk<CR>", "Undo Stage Hunk" },
    },
    r = {
        name = "Runner",
        r = { "<Plug>SnipRun", "Run Code" },
    },
}, { mode = "v", prefix = "," })
