# vim: ft=dockerfile
FROM platypew/pwnpad:lite

ENV USER=pwnpad
USER $USER

# Temporarily uninstall gnu netcat
RUN sudo pacman -R --noconfirm gnu-netcat && \
\
# Install extra software
    sudo pacman -Syu --noconfirm --overwrite='*' arp-scan commix creddump \
         crunch dnsenum dnsrecon enum4linux-ng evil-winrm fping hashcat-utils hping pwnpad/john lbd \
         pwnpad/ligolo-ng ldapenum mimikatz nbtscan ncrack netsed netsniff-ng ngrep \
         onesixtyone rustscan scalpel seclists sleuthkit smbmap socat swaks \
         tcpreplay traceroute wafw00f whatweb whois windows-binaries && \
\
# Fix smbclient
    sudo mkdir /etc/samba && \
    sudo wget -O /etc/samba/smb.conf \
         "https://raw.githubusercontent.com/samba-team/samba/master/examples/smb.conf.default" && \
\
# Reinstall gnu netcat
    yes | sudo pacman -Sdd gnu-netcat && \
\
# Install responder
    sudo pacman -Sdd --noconfirm responder && \
\
# Install netexec
    sudo pacman -S --noconfirm rust && \
    pipx install git+https://github.com/Pennyw0rth/NetExec@v1.4.0 && \
    sudo pacman -Rsc --noconfirm rust && \
    impacket=("DumpNTLMInfo" "Get-GPPPassword" "GetADComputers" "GetADUsers" "GetLAPSPassword" \
    "GetNPUsers" "GetUserSPNs" "addcomputer" "atexec" "changepasswd" "dacledit" "dcomexec" \
    "describeTicket" "dpapi" "esentutl" "exchanger" "findDelegation" "getArch" "getPac" "getST" \
    "getTGT" "goldenPac" "karmaSMB" "keylistattack" "kintercept" "lookupsid" "machine_role" \
    "mimikatz" "mqtt_check" "mssqlclient" "mssqlinstance" "net" "netview" "ntfs-read" "ntlmrelayx" \
    "owneredit" "ping" "ping6" "psexec" "raiseChild" "rbcd" "rdp_check" "reg" "registry-read" \
    "regsecrets" "rpcdump" "rpcmap" "sambaPipe" "samrdump" "secretsdump" "services" "smbclient" \
    "smbexec" "smbserver" "sniff" "sniffer" "split" "ticketConverter" "ticketer" "tstool" "wmiexec" \
    "wmipersist" "wmiquery") && \
    for value in "${impacket[@]}" ; \
        do ln -s /usr/sbin/${value}.py "/home/$USER/.local/bin/impacket-${value}" ; \
    done && \
\
# Install reverse shell generator
    git clone --depth=1 https://github.com/pwnpad/revshellgen.git ~/.local/share/revshellgen && \
    ln -s ~/.local/share/revshellgen/revshellgen ~/.local/bin/revshellgen && \
\
# Install gui stuff
    sudo pacman -S --noconfirm xorg-server-xvfb x11vnc novnc xdotool gnu-free-fonts i3-wm i3status && \
\
# Clean up
    yay -Scc --noconfirm && yay -Rsc --noconfirm $(yay -Qtdq) ; \
    sudo rm -rf /home/$USER/.zshrc.pre-oh-my-zsh /home/$USER/.zsh_history /home/$USER/.bash_profile \
         /home/$USER/.wget-hsts /home/$USER/.bash_logout /home/$USER/.bundle /tmp/* /var/cache \
         /home/$USER/.cache/pip /home/$USER/.cache/yay /home/$USER/.npm /var/log/* \
         /home/$USER/.zcompdump-buildkitsandbox* ; \
\
    sudo updatedb

USER root
